use snforge_std::{CheatSpan, cheat_caller_address, declare, DeclareResultTrait, ContractClassTrait, start_cheat_block_timestamp, stop_cheat_block_timestamp};
use starknet::{ContractAddress, SyscallResultTrait};
use gameshield::gameshield::{IGameShieldDispatcher, IGameShieldDispatcherTrait};

const ORGANIZER: felt252 = 'organizer'; const WINNER: felt252 = 'winner'; const OTHER: felt252 = 'other'; const POOL: felt252 = 'privacy_pool'; const TITLE: felt252 = 'Speedrun'; const CRITERIA: felt252 = 'criteria-v1'; const REWARD: u128 = 1_000; const DEADLINE: u64 = 100;
fn addr(x: felt252) -> ContractAddress { x.try_into().unwrap() }
fn caller(g: ContractAddress, x: felt252) { let calls: u32 = 10; cheat_caller_address(g, addr(x), CheatSpan::TargetCalls(calls.try_into().unwrap())); }
fn game() -> ContractAddress { let c = declare("GameShield").unwrap().contract_class(); let (a, _) = c.deploy(@array![addr(POOL).into()]).unwrap_syscall(); a }
fn token() -> ContractAddress { let c = declare("TestToken").unwrap().contract_class(); let (a, _) = c.deploy(@array![]).unwrap_syscall(); a }
fn create(g: ContractAddress, t: ContractAddress, grace: u64, expiry: u64) -> u64 { caller(g, ORGANIZER); IGameShieldDispatcher { contract_address: g }.create_campaign(t, REWARD, DEADLINE, CRITERIA, TITLE, grace, expiry) }
fn custom(g: ContractAddress, t: ContractAddress, reward: u128, deadline: u64, title: felt252) -> u64 { caller(g, ORGANIZER); IGameShieldDispatcher { contract_address: g }.create_campaign(t, reward, deadline, CRITERIA, title, 0, 0) }
fn fund(g: ContractAddress, t: ContractAddress, id: u64, amount: u128) { ITestTokenDispatcher { contract_address: t }.mint(g, amount.into()); caller(g, POOL); let d = IGameShieldDispatcher { contract_address: g }.privacy_invoke(id, t, amount); assert!(d.len() == 0, "empty deposit span"); }
fn winner(g: ContractAddress, id: u64, amount: u128, who: felt252) -> u32 { caller(g, ORGANIZER); IGameShieldDispatcher { contract_address: g }.add_winner(id, amount, addr(who)) }
fn balance(t: ContractAddress, a: ContractAddress) -> u256 { ITestTokenDispatcher { contract_address: t }.balance_of(a) }

#[test] fn create_accepts_zero_windows() { let g=game(); let t=token(); let id=create(g,t,0,0); let c=IGameShieldDispatcher {contract_address:g}.get_campaign(id); assert!(c.assignment_grace_period==0); assert!(c.claim_expiry_window==0); }
#[test] #[should_panic] fn create_rejects_zero_token() { let g=game(); let _=custom(g,addr(0),REWARD,DEADLINE,TITLE); }
#[test] #[should_panic] fn create_rejects_zero_reward() { let g=game(); let t=token(); let _=custom(g,t,0,DEADLINE,TITLE); }
#[test] #[should_panic] fn create_rejects_zero_deadline() { let g=game(); let t=token(); let _=custom(g,t,REWARD,0,TITLE); }
#[test] #[should_panic] fn create_rejects_empty_title() { let g=game(); let t=token(); let _=custom(g,t,REWARD,DEADLINE,0); }
#[test] #[should_panic] fn create_rejects_past_deadline() { let g=game(); let t=token(); start_cheat_block_timestamp(g,101); let _=custom(g,t,REWARD,DEADLINE,TITLE); stop_cheat_block_timestamp(g); }

#[test] fn add_winner_stores_address() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let s=winner(g,id,400,WINNER); let w=IGameShieldDispatcher {contract_address:g}.get_winner_slot(id,s); assert!(w.winner_address==addr(WINNER)); assert!(w.amount==400); }
#[test] #[should_panic] fn add_winner_is_organizer_only() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); caller(g,OTHER); let _=IGameShieldDispatcher {contract_address:g}.add_winner(id,1,addr(WINNER)); }
#[test] #[should_panic] fn add_winner_rejects_zero_address() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let _=IGameShieldDispatcher {contract_address:g}.add_winner(id,1,addr(0)); }
#[test] #[should_panic] fn add_winner_rejects_over_allocation() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let _=winner(g,id,1001,WINNER); }
#[test] #[should_panic] fn add_winner_rejects_after_unallocated_sweep() { let g=game(); let t=token(); let id=create(g,t,10,60); fund(g,t,id,REWARD); start_cheat_block_timestamp(g,111); IGameShieldDispatcher {contract_address:g}.sweep_unallocated(id); stop_cheat_block_timestamp(g); let _=winner(g,id,1,WINNER); }

#[test] fn claim_winner_pays_exact_amount() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let s=winner(g,id,400,WINNER); caller(g,WINNER); IGameShieldDispatcher {contract_address:g}.claim_winner(id,s); assert!(balance(t,addr(WINNER))==400); assert!(IGameShieldDispatcher {contract_address:g}.get_winner_slot(id,s).claimed); }
#[test] fn claim_winner_decrements_total_escrowed() { let g=game(); let t=token(); let first=custom(g,t,400,DEADLINE,TITLE); fund(g,t,first,400); let s=winner(g,first,400,WINNER); caller(g,WINNER); IGameShieldDispatcher {contract_address:g}.claim_winner(first,s); let second=custom(g,t,600,DEADLINE,TITLE); fund(g,t,second,600); assert!(IGameShieldDispatcher {contract_address:g}.get_campaign(second).funded, "subsequent funding remains solvent after claim"); }
#[test] #[should_panic] fn claim_winner_non_winner_reverts_NOT_WINNER() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let s=winner(g,id,400,WINNER); caller(g,OTHER); let _=IGameShieldDispatcher {contract_address:g}.claim_winner(id,s); }
#[test] #[should_panic] fn claim_winner_already_claimed_reverts_ALREADY_CLAIMED() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); let s=winner(g,id,400,WINNER); caller(g,WINNER); IGameShieldDispatcher {contract_address:g}.claim_winner(id,s); let _=IGameShieldDispatcher {contract_address:g}.claim_winner(id,s); }
#[test] #[should_panic] fn claim_winner_unfunded_reverts_NOT_FUNDED() { let g=game(); let t=token(); let id=create(g,t,30,60); let _=IGameShieldDispatcher {contract_address:g}.claim_winner(id,0); }
#[test] #[should_panic] fn claim_winner_missing_slot_reverts_SLOT_NOT_FOUND() { let g=game(); let t=token(); let id=create(g,t,30,60); fund(g,t,id,REWARD); caller(g,WINNER); let _=IGameShieldDispatcher {contract_address:g}.claim_winner(id,99); }

#[test] #[should_panic] fn sweep_expired_slot_blocks_original_winner_with_ALREADY_CLAIMED() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); let s=winner(g,id,REWARD,WINNER); start_cheat_block_timestamp(g,121); IGameShieldDispatcher {contract_address:g}.sweep_expired_slot(id,s); stop_cheat_block_timestamp(g); caller(g,WINNER); let _=IGameShieldDispatcher {contract_address:g}.claim_winner(id,s); }
#[test] #[should_panic] fn sweep_unallocated_fails_before_grace() { let g=game(); let t=token(); let id=create(g,t,10,60); fund(g,t,id,REWARD); let _=IGameShieldDispatcher {contract_address:g}.sweep_unallocated(id); }
#[test] fn sweep_unallocated_is_permissionless() { let g=game(); let t=token(); let id=create(g,t,10,60); fund(g,t,id,REWARD); let _=winner(g,id,400,WINNER); caller(g,OTHER); start_cheat_block_timestamp(g,111); IGameShieldDispatcher {contract_address:g}.sweep_unallocated(id); stop_cheat_block_timestamp(g); assert!(IGameShieldDispatcher {contract_address:g}.get_campaign(id).refund_pool==600); }
#[test] #[should_panic] fn sweep_expired_slot_fails_before_window() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); let s=winner(g,id,REWARD,WINNER); let _=IGameShieldDispatcher {contract_address:g}.sweep_expired_slot(id,s); }

#[test] #[should_panic] fn claim_refund_is_organizer_only() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); caller(g,OTHER); let _=IGameShieldDispatcher {contract_address:g}.claim_refund(id); }
#[test] #[should_panic] fn claim_refund_empty_pool_reverts_NOTHING_TO_REFUND() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); let _=IGameShieldDispatcher {contract_address:g}.claim_refund(id); }
#[test] fn claim_refund_drains_and_repeats() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); let a=winner(g,id,400,WINNER); let b=winner(g,id,600,OTHER); start_cheat_block_timestamp(g,121); IGameShieldDispatcher {contract_address:g}.sweep_expired_slot(id,a); stop_cheat_block_timestamp(g); caller(g,ORGANIZER); IGameShieldDispatcher {contract_address:g}.claim_refund(id); assert!(balance(t,addr(ORGANIZER))==400.into()); assert!(IGameShieldDispatcher {contract_address:g}.get_campaign(id).refund_pool==0); start_cheat_block_timestamp(g,141); IGameShieldDispatcher {contract_address:g}.sweep_expired_slot(id,b); stop_cheat_block_timestamp(g); IGameShieldDispatcher {contract_address:g}.claim_refund(id); assert!(balance(t,addr(ORGANIZER))==REWARD.into()); }

#[test] #[should_panic] fn privacy_invoke_rejects_non_pool() { let g=game(); let t=token(); let id=create(g,t,10,20); caller(g,OTHER); let _=IGameShieldDispatcher {contract_address:g}.privacy_invoke(id,t,REWARD); }
#[test] #[should_panic] fn privacy_invoke_rejects_already_funded() { let g=game(); let t=token(); let id=create(g,t,10,20); fund(g,t,id,REWARD); caller(g,POOL); let _=IGameShieldDispatcher {contract_address:g}.privacy_invoke(id,t,REWARD); }
#[test] #[should_panic] fn privacy_invoke_rejects_token_mismatch() { let g=game(); let t=token(); let other=token(); let id=create(g,t,10,20); ITestTokenDispatcher {contract_address:other}.mint(g,REWARD.into()); caller(g,POOL); let _=IGameShieldDispatcher {contract_address:g}.privacy_invoke(id,other,REWARD); }
#[test] #[should_panic] fn privacy_invoke_rejects_amount_mismatch() { let g=game(); let t=token(); let id=create(g,t,10,20); ITestTokenDispatcher {contract_address:t}.mint(g,999.into()); caller(g,POOL); let _=IGameShieldDispatcher {contract_address:g}.privacy_invoke(id,t,999); }

#[starknet::interface] trait ITestToken<T> { fn mint(ref self:T, account:ContractAddress, amount:u256); fn balance_of(self:@T, account:ContractAddress)->u256; fn transfer(ref self:T, recipient:ContractAddress, amount:u256)->bool; }
#[starknet::contract] mod TestToken { use starknet::storage::{StorageMapReadAccess,StorageMapWriteAccess}; use starknet::ContractAddress; #[storage] struct Storage { balances:starknet::storage::Map<ContractAddress,u256> } #[abi(embed_v0)] impl Impl of super::ITestToken<ContractState> { fn mint(ref self:ContractState,account:ContractAddress,amount:u256){self.balances.write(account,self.balances.read(account)+amount);} fn balance_of(self:@ContractState,account:ContractAddress)->u256{self.balances.read(account)} fn transfer(ref self:ContractState,recipient:ContractAddress,amount:u256)->bool{let from=starknet::get_caller_address();let b=self.balances.read(from);assert(b>=amount,'insufficient');self.balances.write(from,b-amount);self.balances.write(recipient,self.balances.read(recipient)+amount);true} } }
